name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install

      - name: Decode and install provisioning profile & certificate
        run: |
          # Create directories
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles

          # Decode .p12 and provisioning profile
          echo "${{ secrets.IOS_CERT_BASE64 }}" | base64 --decode > cert.p12
          echo "${{ secrets.IOS_PROVISION_BASE64 }}" | base64 --decode > profile.mobileprovision

          # Move provisioning profile
          UUID=$(grep -aA1 UUID profile.mobileprovision | grep -io "[-A-F0-9]\{36\}" | head -1)
          mv profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision

          # Create and unlock keychain
          security create-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" ios-build.keychain
          security default-keychain -s ios-build.keychain
          security unlock-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" ios-build.keychain
          security import cert.p12 -k ios-build.keychain -P "${{ secrets.IOS_CERT_PASSWORD }}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "${{ secrets.KEYCHAIN_PASSWORD }}" ios-build.keychain

      - name: Build iOS .ipa
        run: |
          cd ios
          xcodebuild \
            -workspace otagithubactions.xcworkspace \
            -scheme otagithubactions \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $PWD/build/otagithubactions.xcarchive \
            DEVELOPMENT_TEAM=${{ secrets.DEVELOPMENT_TEAM }} \
            CODE_SIGN_IDENTITY="${{ secrets.CODE_SIGN_IDENTITY }}" \
            PRODUCT_BUNDLE_IDENTIFIER=${{ secrets.BUNDLE_ID }} \
            archive

          xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/otagithubactions.xcarchive \
            -exportPath $PWD/build/export \
            -exportOptionsPlist ExportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: ios/build/export/*.ipa







# name: Build iOS App

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-ios:
#     runs-on: macos-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Set up Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 18

#       - name: Install dependencies
#         run: yarn install

#       - name: Install CocoaPods
#         run: |
#           cd ios
#           pod install

#       # Add certificate + provisioning decoding here...

#       - name: Build .ipa
#         run: |
#           cd ios
#           xcodebuild \
#             -workspace otagithubactions.xcworkspace \
#             -scheme otagithubactions \
#             -sdk iphoneos \
#             -configuration Release \
#             -archivePath $PWD/build/App.xcarchive \
#             archive

#           xcodebuild \
#             -exportArchive \
#             -archivePath $PWD/build/App.xcarchive \
#             -exportOptionsPlist ExportOptions.plist \
#             -exportPath $PWD/build/export

#       - name: Upload IPA
#         uses: actions/upload-artifact@v4
#         with:
#           name: ios-ipa
#           path: ios/build/export/*.ipa
